config/routes.rb
Rails.application.routes.draw do
  resources :articles
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/article.rb
class Article < ApplicationRecord
  validates :title, presence: true
  validates :content, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  before_action :find_article, only: [:show, :edit, :update, :destroy]

  def index
    @articles = Article.all
  end

  def show
  end

  def new
    @article = Article.new
  end

  def create
    @article = Article.new(articles_param)
    @article.save
    redirect_to article_path(@article)
  end

  def edit
  end

  def update
    @article.updated = true
    @article.update(articles_param)
    redirect_to article_path(@article)
  end

  def destroy
    @article.destroy
    redirect_to articles_path
  end

  private

  def find_article
    @article = Article.find(params[:id])
  end

  def articles_param
    params.require(:article).permit(:title, :content)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/views/articles/_form.html.erb
<%= simple_form_for(@article) do |f| %>
	<%= f.input :title %>
	<%= f.input :content %>
	<%= f.submit class: "btn btn-primary mr-3" %><%= link_to "back", articles_path, class: "btn btn-outline-primary" %>
<% end %>

app/views/articles/_nav.html.erb
<nav class="navbar sticky-top navbar-expand-lg navbar-light bg-light justify-content-between border-bottom">
  <%= link_to 'Wikinomous', articles_path, class: "navbar-brand text-muted" %>
  <%= link_to 'New Article', new_article_path, class: "nav navbar-nav navbar-right text-muted" %>
</nav>

app/views/articles/edit.html.erb
<%= render "nav", article: @article %>

<div class="container">
  <h1>Edit <%= @article.title %></h1>
  <%= render "form", article: @article %>
</div>

app/views/articles/index.html.erb
<%= render "nav", article: @article %>

<div class="container">
  <% @articles.each do |article| %>
    <div class="card border-0">
      <%= link_to "<h2>#{article.title}</h2>".html_safe, article_path(article) %>
      <p><%= article.content %></p>
    </div>
  <% end %>

app/views/articles/new.html.erb
<%= render "nav", article: @article %>

<div class="container">
  <h1>New article</h1>
  <%= render "form", article: @article %>
</div>

app/views/articles/show.html.erb
<%= render "nav", article: @article %>

<div class="container">
  <div class="card border-0">
	  <% if @article.updated == true %>
      <div id ="alert" class="alert alert-success justify-content-between" style="display:flex;" role="alert">
        <h5>Article was successfully updated</h5><i class="fas fa-times"></i>
      </div>
		<% end %>
    <div class="card-header border-bottom bg-transparent">
      <div class= "card-title">
				<h2><%= @article.title %></h2>
				<%= link_to '<i class="fas fa-pencil-alt" aria-hidden="true"></i>
'.html_safe, edit_article_path %>
				<%= link_to '<i class="far fa-trash-alt"></i>'.html_safe, article_path(@article), method: :delete, data: {confirm: "are you sure you want to delete #{@article.title}?"}
				%>
       </div>
    </div>
    <div class="card-body">
      <p class ="card-text"><%= @article.content %></p>
			<%= link_to "back", articles_path %>
    </div>	
  </div>
</div>

<script>
  let xButton = document.querySelector(".fa-times");
	xButton.eventListener("click", (event){
    document.getElementById("#alert").style.display="none";
	});
</script>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsWikinimous</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.6.0/dist/css/bootstrap.min.css" integrity="sha384-B0vP5xmATw1+K9KRQjQERJvTumQW0nPEzvF6L/Z6nronJ3oUOFUFpCjEUQouq2+l" crossorigin="anonymous">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.3/css/all.min.css" integrity="sha512-iBBXm8fW90+nuLcSKlbmrPcLa0OT92xO1BIsZ+ywDWZCvqsWgccV3gFoRBv0z+8dLJgyAHIhR35VZc2oM/gI1w==" crossorigin="anonymous" />
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>